language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.3
install: gem install hoe
script: rake test
notifications:
  email: false
